# Generated by Django 5.0.1 on 2024-02-05 21:05

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('award_count', models.CharField(max_length=3)),
                ('tour_count', models.CharField(max_length=4)),
                ('travel_count', models.IntegerField()),
                ('team_member_count', models.CharField(max_length=5)),
                ('is_active', models.BooleanField(default=False, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TourType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Tours', 'Tours'), ('Excursions', 'Excursions'), ('Destinations', 'Destinations')], default='Tours', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='galleries', to='app.language')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destinations', to='app.about')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destinations', to='app.language')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='countries', to='app.language')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blog_tags', to='app.language')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_new', models.BooleanField(default=True)),
                ('tags', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='app.blogtag')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blogs', to='app.language')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='about',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abouts', to='app.language'),
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('phone', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True, unique=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='menu', to='app.language')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PeopleSay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('comment', models.TextField()),
                ('avatar', models.ImageField(upload_to='about/people/')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='people_says', to='app.language')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', ckeditor.fields.RichTextField()),
                ('price', models.IntegerField()),
                ('is_hot', models.BooleanField(default=False)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tours', to='app.country')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tours', to='app.language')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tours', to='app.tourtype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TourEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', ckeditor.fields.RichTextField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='app.language')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='app.tour')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
