# Generated by Django 5.0.1 on 2024-02-05 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='menu',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
