# Generated by Django 5.0.1 on 2024-02-05 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_menu_end_time_alter_menu_start_time'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together={('is_active', 'language')},
        ),
    ]
