# Generated by Django 5.0.1 on 2024-02-05 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_menu_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together={('language',)},
        ),
        migrations.AlterField(
            model_name='menu',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
