# Generated by Django 5.0.1 on 2024-02-05 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_tour_preview_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
