# Generated by Django 5.0.1 on 2024-02-06 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_blog_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='is_new',
            new_name='is_popular',
        ),
    ]
