# Generated by Django 5.0.1 on 2024-02-07 23:13

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_about_address_about_address_google'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='description',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='image',
            field=models.ImageField(null=True, upload_to='countries/'),
        ),
    ]
