# Generated by Django 5.0.1 on 2024-02-11 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='show_price',
            field=models.BooleanField(default=False),
        ),
    ]
