# Generated by Django 5.0.1 on 2024-02-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_tour_show_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='country',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
